# Generated by Django 4.2.6 on 2023-10-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_image_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Name',
        ),
    ]
