# Generated by Django 4.2.6 on 2023-10-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_userdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
    ]
