# Generated by Django 4.2.6 on 2023-10-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_userdata_email_alter_userdata_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.image'),
        ),
    ]
