# Generated by Django 4.2.6 on 2023-10-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_image_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='phone',
            new_name='telefonnummer',
        ),
    ]
